### ISSUE TITLE
Noroot support

### ISSUE THREAD

**Issue by fervi** [guardianproject/lildebi#100]
Hello!

Some "Linux on Android" software support Noroot option
So you can use Debian (for example) without rooted phone using fakeroot

For example: Debian noroot or GnuRoot Wheezy

I think - lildebi should also support Noroot option

Thanks for reading
Fervi

**Comment by SDkie** [comment]
@eighthave @cedric-vincent @fervi 
Proot provides implementation for chroot, mount --bind, and binfmt_misc only. I think so we can't run cdebootstrap command inside the application. and cuntubuntu uses already created image.
So if we have to provide noroot support we have to remove cdebootstrap.
What are your views on this?

[1] https://github.com/pelya/cuntubuntu

**Comment by eighthave** [comment]
For no-root support, it'll just have to not run `cdebootstrap`, I can't see why it would have to be removed.  I think the tricky bit will be managing the mount point, since it'll have to be in `/data/data/info.guardianproject.lildebi/debian`.  That's the only place a noroot app will have permission to write.

What's the advantage of adding no-root support to Lil' Debi if it is already supported in that other app?

**Comment by SDkie** [comment]
I was thinking it will be very userful if we can add support for non-rooted phones without reducing the functionality of lildebi. 
Should we close this issue ?

**Comment by eighthave** [comment]
If there is already another free, open source app that does no root Debian
installs, I think it is better to keep Lil' Debi focused on what it does: a
full, integrated Debian install.

**Comment by eighthave** [comment]
I'm going to close this for now. If someone does think of a good reason why no-root fits into the goals of Lil' Debi, then I'm happy to reconsider.
