### ISSUE TITLE
support LXDE

### ISSUE THREAD

**Issue by eighthave** [guardianproject/lildebi#123]
LXDE is a lightweight user environment that should work nicely on Android devices.  In order for it to work on Android, the `xrdp` process needs to have network permissions, i.e. `adduser xrdp inet`

**Comment by TuningGuide** [comment]
Hy eighthave, to overcome my problems in the other issues I created an 600MB image in Android 4.4.4 and resized it to 4GB with dd and resize2fs on an debian virtual machine (on mac [now i only need microsoft to cover all big system]) ;) Anyway after installing lxde I can't connect to the debian via ssh anymore. Could it have something to do with dbus or line:
```
[ ok ] Starting network connection manager: NetworkManager.
```
Regards

**Comment by TuningGuide** [comment]
Actually the debian on my phone can't connect to the network anymore.

**Comment by TuningGuide** [comment]
it turned out that
1. /etc/fstab was missing: touch /etc/fstab
2. the networking interface was missing before lxde but was set up after network manager was setup:
echo -e "\nauto wlan0\niface wlan0 inet dhcp" >> /etc/network/interfaces"
and
/etc/init.d/networking restart

now it works again

**Comment by eighthave** [comment]
My guess is that it is probably not a good idea to have Debian managing the network interfaces in a chroot on an Android device.  You'll likely end up with Android and Debian fighting over configuring the network interfaces, since they share a kernel and hardware. Neither OS was designed to expect another parallel OS changing the hardware config at the same time.

**Comment by TuningGuide** [comment]
(For Documentation) With wheezy I hat to do following things to get lxde and xrdp running:
xrdp-side:
apt-get install xrdp
then change in /etc/init.d/xrdp line
start-stop-daemon --start --quiet --oknodo --pidfile /var/run/xrdp/xrdp.pid --chuid xrdp:xrdp --exec /usr/sbin/xrdp
to
start-stop-daemon --start --quiet --oknodo --pidfile /var/run/xrdp/xrdp.pid --exec /usr/sbin/xrdp
(thats for sure a selinux problem)
but otherwise xrdp will not run as service

lxde-side:
copy everything from /etc/xdg/lxpanel/LXDE to ~/.config/lxpanel/LXDE
