### ISSUE TITLE
Fails to detect superuser when built into the ROM

### ISSUE THREAD

**Issue by nroach44** [guardianproject/lildebi#148]
I'm suspicious that this only applies to my particular rom/distro, as you'd think there would be more cases of it applying to cyanogenmod and such. EDIT: I now see the little "if cyanogen" lines, I'm going to try something...

I'm on a custom built CarbonROM mako kitkat build. CarbonROM integrates superuser into the Settings menu (and does it through systemUI, iirc) and thus it doesn't have a package name.

Since 0.5.1 I have not been able to start my debian image.

If possible, could there be an option to ignore the superuser check or just check by the old method (and try elvating) if the other checks fail?

**Comment by cjeanneret** [comment]
Heya!

I have the very same problem on my SlimKat nexus7 device… Instead of white-listing ROMs, it might be better to add a smartest test, like, for exemple, the one provided by [this root library](https://github.com/dschuermann/superuser-commands/blob/master/libraries/RootCommands/src/main/java/org/sufficientlysecure/rootcommands/RootCommands.java#L32)…

I'm pretty sure it will be faster and smarter.

Cheers,

C.

**Comment by eighthave** [comment]
yes, Lil' Debi should definitely use libsuperuser or RootCommands, its really
just a matter of someone doing the work.  I only use koush's Superuser, and
its been reliable for me.
